debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8080"

[api]
entryPoint = "api"

[acme]
email = "510830568@qq.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "liangyoult.com"
  sans = ["two.liangyoult.com", "three.liangyoult.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "liangyoult.com"
watch = true
exposedByDefault = false
swarmmode=true

